YLP-858 Some algorithm settings are visible on the daily view
mdblp/tide-whisperer pull request #42
Opened 2021-06-28 14:46 UTC by CedricPerotto

2021-06-28 16:42 UTC, Nas84 approved these changes
LGTM

2021-06-29 06:46 UTC, yvon-dblg reviewed
I would probably have created statically the levels arrays.
To avoid allocation at each run and conversion for each parameter from int to string.
(Not tested yet)

```golang
var (
	// Parameters level to keep in api response (int value)
	paramLevelFilterInt = [...]int{1}
	// Parameters level to keep in api response (string value)
	paramLevelFilterStr = [...]string{"1"}
)
```

Call to the GetDiabeloopParametersHistory:
```golang
		writeParams.parametersHistory, err = a.store.GetDiabeloopParametersHistory(ctx, userID, paramLevelFilterInt[:])
```

Filter for the daily view:
```golang
			if datumType == "deviceEvent" {
				datumSubType, haveSubType := datum["subType"].(string)
				if haveSubType && datumSubType == "deviceParameter" {
					datumLevel, haveLevel := datum["level"].(string)
					if haveLevel && !contains(paramLevelFilterStr[:], datumLevel) {
						continue
					}
				}
			}
```

2021-06-29 09:19 UTC, franck-fourel requested changes
some little changes based on what devdroid specifications

2021-06-29 09:19 UTC, franck-fourel commented on data/api_v1.go
> +	parameterLevelFilter = append(parameterLevelFilter, 1)
```suggestion
	parameterLevelFilter := [2]int{1, 2}
```

2021-06-29 09:19 UTC, franck-fourel commented on data/api_v1_test.go
> +{"id":"02","level":"1","subType":"deviceParameter","time":"2021-01-10T00:00:01.000Z","type":"deviceEvent","uploadId":"00"},
```suggestion
{"id":"01","level":"1","subType":"deviceParameter","time":"2021-01-10T00:00:01.000Z","type":"deviceEvent","uploadId":"00"},
{"id":"02","level":"2","subType":"deviceParameter","time":"2021-01-10T00:00:02.000Z","type":"deviceEvent","uploadId":"00"},
```

2021-06-29 09:19 UTC, franck-fourel commented on data/api_v1_test.go
> +		"{\"id\":\"03\",\"uploadId\":\"00\",\"time\":\"2021-01-10T00:00:02.000Z\",\"type\":\"deviceEvent\",\"subType\":\"deviceParameter\",\"level\":\"2\"}",
```suggestion
		"{\"id\":\"01\",\"uploadId\":\"00\",\"time\":\"2021-01-10T00:00:01.000Z\",\"type\":\"deviceEvent\",\"subType\":\"deviceParameter\",\"level\":\"1\"}",
		"{\"id\":\"02\",\"uploadId\":\"00\",\"time\":\"2021-01-10T00:00:02.000Z\",\"type\":\"deviceEvent\",\"subType\":\"deviceParameter\",\"level\":\"2\"}",
		"{\"id\":\"03\",\"uploadId\":\"00\",\"time\":\"2021-01-10T00:00:03.000Z\",\"type\":\"deviceEvent\",\"subType\":\"deviceParameter\",\"level\":\"3\"}",```

2021-07-01 06:59 UTC, franck-fourel approved these changes

2021-07-01 06:59 UTC, merged