no settings found is not raising an error, but just logging a message
mdblp/tide-whisperer pull request #69
Opened 2022-10-20 15:29 UTC by yanngit

2022-10-31 15:00 UTC, CedricPerotto requested changes

2022-11-02 08:58 UTC, yanngit commented on data/api_v1_data_helper.go
> +		"basalsecurityrofile": p.basalSecurityProfile,
typo fixed thx :) Changed to match the current name which is not camel case :)

2022-11-03 10:02 UTC, yanngit commented on data/api_v1_data_helper.go
> +		if !strings.Contains(err.Error(), strconv.Itoa(http.StatusNotFound)) {
yep, doing it

2022-11-03 14:27 UTC, CedricPerotto approved these changes

2022-11-03 16:05 UTC, merged