YLP-2277 Convert glycemia values into user defined unit (mmol/L <-> mg/dL)
mdblp/tide-whisperer pull request #79
Opened 2023-04-06 14:55 UTC by yanngit

2023-04-18 16:23 UTC, CedricPerotto requested changes

2023-04-19 08:27 UTC, yanngit commented on usecase/helper.go
> +		}
Fixed

2023-04-19 12:08 UTC, ydrisR requested changes

2023-04-19 12:08 UTC, ydrisR commented on Jenkinsfile
> +//             when { branch "dblp" }
Uncomment and change dblp -> main

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper.go
> +			if datum["units"] != bgUnit {
we should also check that datum["units"] is MgdL or MmolL

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper.go
> +			if paramChange.PreviousUnit != bgUnit && paramChange.PreviousValue != "" {
same here we should also check that paramChange.PreviousUnit is MgdL or MmolL

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper.go
> +			if hp.Unit != bgUnit {
same here we should also check that hp.Unit is MgdL or MmolL

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper.go
> +			if hp.PreviousUnit != bgUnit {
same here we should also check that hp.PreviousUnit is MgdL or MmolL

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper.go
> +
tide-v2 has this implementation in order to limit the number of digits in the float part:

```go
func convertToMmoll(value float64) float64 {
	roundedValue := math.Round(value / schema.MmolLToMgdLConversionFactor * schema.MmolLToMgdLPrecisionFactor)
	floatValue := roundedValue / schema.MmolLToMgdLPrecisionFactor
	return floatValue
}
```

2023-04-19 14:13 UTC, CedricPerotto commented on usecase/helper_test.go
> +func Test_getMgdl(t *testing.T) {
No tests added for getMmol ?

2023-04-24 09:41 UTC, CedricPerotto requested changes

2023-04-24 09:41 UTC, CedricPerotto commented on usecase/patientData.go
> +		// The given of hypo/hyper values
Is it a replace all error ?

2023-04-24 09:41 UTC, CedricPerotto commented on usecase/patientData.go
> +		Unit  string `json:"given" bson:"given"`
Same here, I don't get why this field changes from unit to given...

2023-04-24 09:41 UTC, CedricPerotto commented on api/patientDataController.go
> +		Ctx:                        ctx,
passing context in structs is not recommended 
https://go.dev/blog/context-and-structs#Storing%20Context%20in%20Structs%20Leads%20to%20Confusion

2023-04-24 09:41 UTC, CedricPerotto commented on usecase/patientData.go
> +					/*For wizard, we don't have anymore fields in mmol, so we're changing the given but no conversion is done.
less impact but looks like the unit -> given replace may be not appropriate here

2023-04-24 15:59 UTC, merged